# Generated by Django 5.0.2 on 2024-07-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
